/**
 * Bluetooth Laser Barcode / QR Scanner Manager
 * Supports:
 * 1. Smart Payload Extraction (JSON QR, URL query params, Chilean Plates, Ticket IDs, SKUs)
 * 2. HID Keyboard Wedge Mode with Burst Interception & Form-Submit Prevention
 * 3. Web Bluetooth API for BLE Scanners
 * 4. Audio Beep Synthesizer for instant audible confirmation
 */

export interface ScannedPayload {
  raw: string;
  ticketNumber?: string;
  plate?: string;
  spotNumber?: number;
  sku?: string;
  type: 'ticket' | 'plate' | 'sku' | 'url' | 'json' | 'generic';
}

export interface BluetoothScannerState {
  isConnected: boolean;
  deviceName: string | null;
  mode: 'web_bluetooth' | 'hid_keyboard' | 'disconnected';
  lastScannedCode: string | null;
  lastPayload: ScannedPayload | null;
  lastScannedAt: string | null;
  totalScans: number;
}

type ScanCallback = (code: string, payload: ScannedPayload) => void;

export function parseScannedCode(rawCode: string): ScannedPayload {
  const clean = rawCode.trim();
  if (!clean) {
    return { raw: '', type: 'generic' };
  }

  // 1. Try parsing JSON (Generated by Bamo Garage QR or external QR systems)
  if ((clean.startsWith('{') && clean.endsWith('}')) || clean.includes('"ticket"') || clean.includes('"plate"')) {
    try {
      const parsed = JSON.parse(clean);
      const ticket = parsed.ticket || parsed.ticketNumber || parsed.tkt || parsed.ticketId;
      const plate = parsed.plate || parsed.patente || parsed.placa;
      const spot = parsed.spot || parsed.spotNumber || parsed.puesto;
      const sku = parsed.sku || parsed.productId;

      return {
        raw: clean,
        ticketNumber: ticket ? String(ticket).toUpperCase() : undefined,
        plate: plate ? String(plate).toUpperCase().replace(/[^A-Z0-9-]/g, '') : undefined,
        spotNumber: spot ? parseInt(String(spot), 10) : undefined,
        sku: sku ? String(sku).toUpperCase() : undefined,
        type: 'json',
      };
    } catch (e) {
      // Not valid JSON, continue to URL / text parsing
    }
  }

  // 2. Try parsing URL (e.g. scanned from phone or QR containing full link)
  if (clean.includes('?') && (clean.includes('ticket=') || clean.includes('plate=') || clean.includes('spot='))) {
    try {
      const queryString = clean.includes('?') ? clean.split('?')[1] : clean;
      const params = new URLSearchParams(queryString);
      const ticket = params.get('ticket') || params.get('tkt');
      const plate = params.get('plate') || params.get('patente');
      const spot = params.get('spot') || params.get('puesto');
      const sku = params.get('sku');

      return {
        raw: clean,
        ticketNumber: ticket ? ticket.toUpperCase() : undefined,
        plate: plate ? plate.toUpperCase().replace(/[^A-Z0-9-]/g, '') : undefined,
        spotNumber: spot ? parseInt(spot, 10) : undefined,
        sku: sku ? sku.toUpperCase() : undefined,
        type: 'url',
      };
    } catch (e) {
      // Continue
    }
  }

  const upper = clean.toUpperCase();

  // 3. Ticket Pattern (e.g. TKT-1234, TK-123, TICKET-001)
  if (upper.startsWith('TKT-') || upper.startsWith('TK-') || upper.startsWith('TICKET-')) {
    return {
      raw: clean,
      ticketNumber: upper,
      type: 'ticket',
    };
  }

  // 4. SKU Pattern (e.g. SKU-123, ACC-LAV-01)
  if (upper.startsWith('SKU-') || upper.startsWith('ACC-') || upper.startsWith('PROD-')) {
    return {
      raw: clean,
      sku: upper,
      type: 'sku',
    };
  }

  // 5. Chilean License Plate Pattern (e.g. BBCL-12, BBCL12, CL-8921, CL8921, AA1234)
  const plateClean = upper.replace(/[^A-Z0-9]/g, '');
  if ((plateClean.length === 5 || plateClean.length === 6) && /^[A-Z0-9]+$/.test(plateClean)) {
    return {
      raw: clean,
      plate: upper,
      type: 'plate',
    };
  }

  return {
    raw: clean,
    ticketNumber: upper,
    type: 'generic',
  };
}

class BluetoothScannerManager {
  private listeners: Set<ScanCallback> = new Set();
  private stateListeners: Set<(state: BluetoothScannerState) => void> = new Set();
  private bluetoothDevice: any = null;
  private buffer: string = '';
  private lastKeyTime: number = 0;
  private keyIntervals: number[] = [];
  private isInitialized: boolean = false;
  private scanSoundEnabled: boolean = true;

  private state: BluetoothScannerState = {
    isConnected: true, // HID Keyboard emulation is always active by default
    deviceName: 'Lector Láser HID / Bluetooth Activo',
    mode: 'hid_keyboard',
    lastScannedCode: null,
    lastPayload: null,
    lastScannedAt: null,
    totalScans: 0,
  };

  constructor() {
    this.initKeyboardListener();
  }

  private playBeep(success: boolean = true) {
    if (!this.scanSoundEnabled || typeof window === 'undefined') return;
    try {
      const AudioCtx = window.AudioContext || (window as any).webkitAudioContext;
      if (!AudioCtx) return;
      const ctx = new AudioCtx();
      const osc = ctx.createOscillator();
      const gain = ctx.createGain();

      osc.type = success ? 'sine' : 'sawtooth';
      osc.frequency.setValueAtTime(success ? 1760 : 440, ctx.currentTime);
      if (success) {
        osc.frequency.setValueAtTime(2637, ctx.currentTime + 0.08);
      }

      gain.gain.setValueAtTime(0.12, ctx.currentTime);
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.16);

      osc.connect(gain);
      gain.connect(ctx.destination);

      osc.start();
      osc.stop(ctx.currentTime + 0.16);
    } catch (e) {
      // Audio context may require previous user interaction
    }
  }

  private initKeyboardListener() {
    if (this.isInitialized || typeof window === 'undefined') return;
    this.isInitialized = true;

    window.addEventListener(
      'keydown',
      (e: KeyboardEvent) => {
        const now = Date.now();
        const diff = now - this.lastKeyTime;
        this.lastKeyTime = now;

        // Check if fast scanner keystrokes
        if (diff > 120) {
          // New input stream started
          this.keyIntervals = [];
        } else {
          this.keyIntervals.push(diff);
        }

        // Scanner detection: if key is Enter
        if (e.key === 'Enter') {
          if (this.buffer.length >= 2) {
            // Check if this was a fast scanner burst (average interval < 70ms)
            const avgInterval =
              this.keyIntervals.length > 0
                ? this.keyIntervals.reduce((a, b) => a + b, 0) / this.keyIntervals.length
                : 100;

            const isLikelyScanner = avgInterval < 75 || this.buffer.length > 8;

            if (isLikelyScanner) {
              // Prevent accidental form submits or button clicks
              e.preventDefault();
              e.stopPropagation();
            }

            const scannedCode = this.buffer.trim();
            this.buffer = '';
            this.keyIntervals = [];
            this.handleCodeReceived(scannedCode);
          } else {
            this.buffer = '';
            this.keyIntervals = [];
          }
          return;
        }

        // Ignore modifier keys
        if (e.key.length > 1) {
          if (diff > 120) this.buffer = '';
          return;
        }

        // Accumulate buffer
        if (diff > 120) {
          this.buffer = e.key;
        } else {
          this.buffer += e.key;
        }
      },
      true
    );
  }

  public handleCodeReceived(rawCode: string) {
    const cleanCode = rawCode.trim();
    if (!cleanCode) return;

    const payload = parseScannedCode(cleanCode);

    this.playBeep(true);

    this.state = {
      ...this.state,
      lastScannedCode: payload.ticketNumber || payload.plate || payload.sku || cleanCode.toUpperCase(),
      lastPayload: payload,
      lastScannedAt: new Date().toISOString(),
      totalScans: this.state.totalScans + 1,
    };

    this.notifyState();

    // Dispatch global event for listeners
    if (typeof window !== 'undefined') {
      window.dispatchEvent(
        new CustomEvent('laser_qr_scanned', {
          detail: { code: cleanCode, payload, timestamp: new Date().toISOString() },
        })
      );
    }

    // Call registered subscribers safely
    this.listeners.forEach((callback) => {
      try {
        callback(cleanCode, payload);
      } catch (err) {
        console.error('Safe scanner subscriber execution error:', err);
      }
    });
  }

  public async connectWebBluetooth(): Promise<{ success: boolean; message: string }> {
    if (typeof navigator === 'undefined' || !(navigator as any).bluetooth) {
      return {
        success: false,
        message:
          'Tu navegador no soporta Web Bluetooth API directamente, pero el modo Lector Láser HID está 100% activo en segundo plano.',
      };
    }

    try {
      const device = await (navigator as any).bluetooth.requestDevice({
        acceptAllDevices: true,
        optionalServices: ['generic_access', 'battery_service', '0000180f-0000-1000-8000-00805f9b34fb'],
      });

      if (device) {
        this.bluetoothDevice = device;
        this.state = {
          ...this.state,
          isConnected: true,
          deviceName: device.name || 'Lector Láser Bluetooth',
          mode: 'web_bluetooth',
        };
        this.notifyState();
        this.playBeep(true);
        return {
          success: true,
          message: `Lector Bluetooth "${device.name || 'Conectado'}" emparejado con éxito.`,
        };
      }

      return { success: false, message: 'No se seleccionó ningún dispositivo Bluetooth.' };
    } catch (err: any) {
      return {
        success: false,
        message: err.message || 'Error al emparejar el dispositivo Bluetooth.',
      };
    }
  }

  public disconnectWebBluetooth() {
    if (this.bluetoothDevice && this.bluetoothDevice.gatt?.connected) {
      this.bluetoothDevice.gatt.disconnect();
    }
    this.bluetoothDevice = null;
    this.state = {
      ...this.state,
      isConnected: true,
      deviceName: 'Lector Láser HID / Bluetooth Activo',
      mode: 'hid_keyboard',
    };
    this.notifyState();
  }

  public onScan(callback: ScanCallback): () => void {
    this.listeners.add(callback);
    return () => {
      this.listeners.delete(callback);
    };
  }

  public subscribeState(callback: (state: BluetoothScannerState) => void): () => void {
    this.stateListeners.add(callback);
    callback(this.state);
    return () => {
      this.stateListeners.delete(callback);
    };
  }

  public getState(): BluetoothScannerState {
    return this.state;
  }

  private notifyState() {
    this.stateListeners.forEach((cb) => {
      try {
        cb(this.state);
      } catch (e) {}
    });
  }

  public triggerTestScan(code: string = 'GARAGE-DEMO-99') {
    this.handleCodeReceived(code);
  }
}

export const scannerManager = new BluetoothScannerManager();
export const bluetoothScanner = scannerManager;
